export const env = {
  API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
  CHROMIA_URL: process.env.NEXT_PUBLIC_CHROMIA_URL,
  BLOCKCHAIN_RID: process.env.NEXT_PUBLIC_BLOCKCHAIN_RID,
  FEE_ASSET_ID: process.env.NEXT_PUBLIC_FEE_ASSET_ID,
  FEE_ASSET_SYMBOL: process.env.NEXT_PUBLIC_FEE_ASSET_SYMBOL,
};